#include <iostream>
#include <string>
#include <vector>
using namespace std;

void initialize(vector<int>& lookup, string s) {
    int ptr1 = 0;

    for(int i = 1; i < s.size(); ++i) {
        if(s[ptr1] == s[i]) {
            lookup[i] = ++ptr1;

        } else {
            lookup[i] = 0;
            ptr1 = 0;
        }
    }
}

bool solve(string s1, string s2) {
    int index1 = 0, index2 = 0;
    int sz1 = s1.size();
    int sz2 = s2.size();
    bool flag = true;
    vector<int>lookup(sz2);
    initialize(lookup, s2);
    
    while(index1 < sz1 && index2 < sz2) {
        if(s1[index1++] == s2[index2]) {
            index2++;
        }
        // mismatched...
        else {
            if(index2 > 0){
                index2 = lookup[index2 - 1];
                index1 -= 1;
            }
        }
    }
    return index2 == sz2 ;
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(NULL);
    cout.tie(NULL);

    int T;
    cin >> T;

    while(T--) {
        string s1, s2;
        cin >> s1 >> s2;

        cout << solve(s1, s2) << "\n";
    }

    return 0;
}

/*
TEST CASES :
12
ABABDABACDABABCABAB
ABABCABAB
AKDSJNDVNKDJAKVFNFAKDSJNDVNKDJAKVFNFNKAAKDSJNDVNKDJAKVFNFNKAAKDSJNDVNKDJAKVFNFNKAAKDSJNDVNKDJAKVFNFNKAFJADSJNDVNKDJAKVFNFNKAFJVAKDSJNDVNKDJAKVFNFNKAFAKDSJNDVNKDJAKVFNFNKAKDSJNDVNKDJAKVFKAFJVAKDSJNDVNKDJAKVFNFNKAFAKDSJNDVNKDJAKVFNFNKAFJAKDSJNDVNKDJAKVFNFNKAFJAKDSJNDVNKDJAKVAKDSJNDVNKDJAKVFNFNKAKDSJNDVNKDJAKVFNFNKAFJV
AKDSJNDVNKDJAKVFNFNKAFJV
AAAAA
A
B
B
ERDE
RD
rtrfr
eree
err
eefeeffffffff
eefdfdfdfgfgfgffg
rf
er
ytyty
tyu
tyu
adsakjadsavdnfkadsakjjdadadsakjadsavdnfkaadsakjadsavdnfadsakjadsavdnfadsakjadsavdnfkadsakadsakjadsavdnfkaadsakjadsavdnfkadsakjjdadsaadsakjadsavdnfkad
adsakjadsavdnfkadsakjjdadsa
aajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjaajdnjabvfhjvbfdjjfaajdnjabvfhaajdnjabvfhjvaajdnjabvfhjvaajdnjabaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdjjfaajdnjabvfhjvbfdj
aajdnjabvfhjvbfdjjfd
*/